### ISSUE TITLE
Schema is missing

### ISSUE THREAD

**Issue by prashanth234** [ptbang/django-graphene-auth#1]
# Prerequisites

* [*] Is it a bug?
* [ ] Is it a new feature?
* [ ] Is it a a question?
* [ ] Can you reproduce the problem?
* [ ] Are you running the latest version?
* [ ] Did you check for similar issues?
* [ ] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/PedroBern/django-graphql-auth/blob/master/CONTRIBUTING.md) guide.

# Description

Description of the bug - 

Couldn't import these queries

from graphql_auth.schema import UserQuery, MeQuery

# Steps to Reproduce

If we need to reproduce and you don't provide steps for it, it will be closed. Alternatively, you can link a repo with the code to run your issue.

1. Try to import - from graphql_auth.schema import UserQuery, MeQuery
2. These are not found

## Expected behavior

What you expected to happen

Should import UserQuery, MeQuery schemas.

## Actual behavior

What actually happened

# Requirements

Paste the packages you are using, you can get this information from executing `pip freeze`.

**Comment by therealartti** [comment]
UserQuery and MeQuery are to be imported from graphql_auth.queries. That being said, the docs need to get updated.
